### ISSUE TITLE
test_dialog.scn generates an error when it tries to display options

### ISSUE THREAD

**Issue by paraclete-pizza** [StraToN/godot-dialogtreetools#2]
Line 133:
get_parent().get_node("OptionsPanel/ScrollContainer/VBoxContainer").add_child(label)

Generates an error, likely because it is attaching a child to a node that does not exist. There is no 'Scrollcontainer' or 'VBoxContainer' in the scene.

**Comment by StraToN** [comment]
Indeed, some nodes were removed/renamed some time ago, I may have missed them in the code. I'll correct this asap. Thank you !

**Comment by StraToN** [comment]
Many changes occurred in the code. This scene will be remade from scratch.
