### ISSUE TITLE
example

### ISSUE THREAD

**Issue by Themaker482** [StraToN/godot-dialogtreetools#5]
I have some problems undestanding this system, anyone has a useful example about how to use this plugin?
I like the idea but i cant make it work.

Thanks

**Comment by StraToN** [comment]
I am still working on this project, mainly turning it into a Godot plugin for the editor. I am facing some small difficulties, but I should be able to have it working in a few weeks.

As the project morphs into a plugin, I'll also join a couple examples that will describe the use.

Mostly, to give a preview, the plugin features a new node for your scenes, that allows you to draw a graph representing the Dialog tree. This node comes with a specific script that provides simple tree progression functions (which you can redefine yourself if you wish).

I'll push my recent progress soon.

**Comment by StraToN** [comment]
I worked on this the last few days and I finally have a beginning of example if you want to try. Just pull the latest commit.
