### ISSUE TITLE
demo doesn't appear to work

### ISSUE THREAD

**Issue by nowakf** [StraToN/godot-dialogtreetools#6]
I've been trying to get this running for a couple of hours, and have had the following problems: 
-importing the plugin is straightforward, but there's no directions as to how to actually use it. I discovered right-clicking to edit the dialog tree by accident. 
-there's no information about how to link the dialog tree to anything else, and
-the demo doesn't work, so no help there.
I'd happilly write up a complete guide, if you can tell me to actually get this thing running.

**Comment by StraToN** [comment]
Hello,
I actually have very few time to work on this side-project, so it's still WIP. I do not intend to make a complete documentation until the project reaches a stable state.
I currently have problems in the testing scene as switching from a TreeNode node to another make Godot crash without any log. 

More problematic, I don't know yet how to save the content of a custom node in the scene file, so when you close Godot, you loose your work in the TreeNode. 

These 2 issues must be solved before I can continue.
But I can give you some clues about how it will work : the TreeNode.gd script will provide standard tree-parsing functions that you will be able to call ; or, you can also attach signals to it. That way you will be able to control the dialog tree from other nodes.

**Comment by StraToN** [comment]
Ok, I finally worked a bit more and the `mainscene.tscn` scene in the last commit should give you a very simple example of use. It still need a bit of work, but the essential is here.

**Comment by nowakf** [comment]
Wow, that's great! thanks!
