### ISSUE TITLE
Nonexistent function 'get_json' in base 'control (treetool.gd)'

### ISSUE THREAD

**Issue by Lord-Windy** [StraToN/godot-dialogtreetools#8]
Hi, this tool is perfect for a game I'm making outside of Godot, but it appears the export function isn't working correctly.

When I hit export, either in your sample project or in one I've made I get the error treetool.gd:59 - Invalid call. Nonexistent function 'get_json' in base 'control (treetool.gd)'

I don't know a whole lot about Godot, but I will attempt to fix it on my own if I can. Though really I am hoping you will be able to do it for me.

**Comment by StraToN** [comment]
Oh! You are right, I totally forgot about this export button. Sorry for the inconvenience. 

I am currently on vacation without any computer. I'll be able to fix it as soon as I come back next week.

Until then you can have a look. The json string is located in the resource attached to the TreeNode. Feel free to PR a solution if you wish.

Also I'm eager to see any game made with this tool 😉 thanks !

**Comment by StraToN** [comment]
Ok, problem should be resolved in current master.
