### ISSUE TITLE
All nodes dissapear after importing a JSON file.

### ISSUE THREAD

**Issue by TheRadMatt** [StraToN/godot-dialogtreetools#9]
Here's the issue: I made a short dialog graph, I exported it and then tried to import it. When I did, all nodes disappeared. That's all there is to it really.

**Comment by StraToN** [comment]
Thanks for reporting. I'll retry this asap and fix the problem.

**Comment by StraToN** [comment]
Ok, problem should be fixed in current master. Please retest ;)
